const REPO=()=>process.env.GITHUB_REPO||'orivonatech/gmax';
const BRANCH=()=>process.env.GITHUB_BRANCH||'main';
const LEADS_PATH='gmax-website/data/leads.json',EVENTS_PATH='gmax-website/data/analytics.json';
function useSupabase(){return !!(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY)}
function storageConfigured(){return useSupabase()||!!process.env.GITHUB_TOKEN}
async function gh(url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:'Bearer '+process.env.GITHUB_TOKEN,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'GMAX-Storage','Content-Type':'application/json'}});const d=await r.json();if(!r.ok)throw Error(d.message||'Storage request failed');return d}
async function ghFile(path){return gh('https://api.github.com/repos/'+REPO()+'/contents/'+path+'?ref='+encodeURIComponent(BRANCH()))}
async function ghPut(path,data,message,sha){return gh('https://api.github.com/repos/'+REPO()+'/contents/'+path,{method:'PUT',body:JSON.stringify({message,content:Buffer.from(JSON.stringify(data,null,2)+'\n').toString('base64'),branch:BRANCH(),sha})})}
async function sb(path,opts={}){const h={apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY,'Content-Type':'application/json'};if(opts.method==='POST'||opts.method==='PATCH')h.Prefer='return=representation';const r=await fetch(String(process.env.SUPABASE_URL).replace(/\/$/,'')+'/rest/v1/'+path,{...opts,headers:h});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch(_){d=t}if(!r.ok)throw Error(typeof d==='object'&&d?.message?d.message:'Supabase request failed');return d}
async function getLeads(){if(useSupabase())return await sb('gmax_leads?select=id,name,email,phone,message,status,source,landing_page,referrer,created_at&order=created_at.desc&limit=500');const f=await ghFile(LEADS_PATH),d=JSON.parse(Buffer.from(f.content,'base64').toString('utf8'));return d.leads||[]}
async function createLead(l){if(useSupabase()){const r=await sb('gmax_leads',{method:'POST',body:JSON.stringify({id:l.id,name:l.name,email:l.email,phone:l.phone,message:l.message,status:l.status,source:l.source,landing_page:l.landingPage||'',referrer:l.referrer||'',created_at:l.createdAt})});return Array.isArray(r)?r[0]:r}for(let a=0;a<2;a++){const f=await ghFile(LEADS_PATH),d=JSON.parse(Buffer.from(f.content,'base64').toString('utf8'));d.leads=Array.isArray(d.leads)?d.leads:[];d.leads.unshift(l);d.updatedAt=l.createdAt;if(d.leads.length>500)d.leads=d.leads.slice(0,500);try{await ghPut(LEADS_PATH,d,'lead: add website contact submission',f.sha);return l}catch(e){if(a===1)throw e}}}
async function updateLead(id,status){if(useSupabase()){const r=await sb('gmax_leads?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({status})});return Array.isArray(r)?r[0]:r}for(let a=0;a<2;a++){const f=await ghFile(LEADS_PATH),d=JSON.parse(Buffer.from(f.content,'base64').toString('utf8')),i=(d.leads||[]).findIndex(x=>String(x.id)===id);if(i<0)return null;d.leads[i].status=status;d.updatedAt=new Date().toISOString();try{await ghPut(LEADS_PATH,d,'admin: update lead status',f.sha);return d.leads[i]}catch(e){if(a===1)throw e}}}
async function recordEvent(e){if(useSupabase()){await sb('gmax_events',{method:'POST',body:JSON.stringify({event:e.event,page:e.page,source:e.source||'',session_id:e.sessionId||'',created_at:e.createdAt})});return}for(let a=0;a<2;a++){const f=await ghFile(EVENTS_PATH),d=JSON.parse(Buffer.from(f.content,'base64').toString('utf8')),key=String(e.createdAt).slice(0,10),day=d.days[key]||(d.days[key]={views:0,sessions:[],events:{},pages:{},sources:{},updatedAt:null});day.updatedAt=e.createdAt;day.events=day.events||{};day.pages=day.pages||{};day.sources=day.sources||{};day.sessions=Array.isArray(day.sessions)?day.sessions:[];if(e.event==='page_view'){day.views=(Number(day.views)||0)+1;if(e.sessionId&&!day.sessions.includes(e.sessionId))day.sessions.push(e.sessionId);if(day.sessions.length>1000)day.sessions=day.sessions.slice(-1000);day.pages[e.page]=(day.pages[e.page]||0)+1}else day.events[e.event]=(day.events[e.event]||0)+1;if(e.source)day.sources[e.source]=(day.sources[e.source]||0)+1;d.updatedAt=e.createdAt;try{await ghPut(EVENTS_PATH,d,'analytics: record '+e.event,f.sha);return}catch(err){if(a===1)throw err}}}
async function getEvents(from,to){if(useSupabase())return await sb('gmax_events?select=event,page,source,session_id,created_at&created_at=gte.'+encodeURIComponent(from+'T00:00:00.000Z')+'&created_at=lte.'+encodeURIComponent(to+'T23:59:59.999Z')+'&order=created_at.asc&limit=50000');const f=await ghFile(EVENTS_PATH),d=JSON.parse(Buffer.from(f.content,'base64').toString('utf8'));return {days:d.days||{}}}
async function getLeadsRange(from,to){if(useSupabase())return await sb('gmax_leads?select=id,name,email,phone,message,status,source,landing_page,referrer,created_at&created_at=gte.'+encodeURIComponent(from+'T00:00:00.000Z')+'&created_at=lte.'+encodeURIComponent(to+'T23:59:59.999Z')+'&order=created_at.desc&limit=5000');const all=await getLeads();return all.filter(l=>{const d=new Date(l.createdAt||l.created_at);if(isNaN(d))return false;const k=d.toISOString().slice(0,10);return k>=from&&k<=to})}
module.exports={storageConfigured,useSupabase,getLeads,createLead,updateLead,recordEvent,getEvents,getLeadsRange};
