-- G-MAX production storage schema for Supabase/Postgres
create table if not exists public.gmax_leads (
  id text primary key,name text not null,email text not null,phone text default '',message text not null,
  status text not null default 'New' check (status in ('New','Contacted','Closed')),
  source text default 'Website contact form',landing_page text default '',referrer text default '',
  created_at timestamptz not null default now()
);
create index if not exists gmax_leads_created_at_idx on public.gmax_leads (created_at desc);
create index if not exists gmax_leads_status_idx on public.gmax_leads (status);
create table if not exists public.gmax_events (
  id bigint generated by default as identity primary key,event text not null,page text default '/',
  source text default '',session_id text default '',created_at timestamptz not null default now()
);
create index if not exists gmax_events_created_at_idx on public.gmax_events (created_at desc);
create index if not exists gmax_events_event_idx on public.gmax_events (event);
alter table public.gmax_leads enable row level security;
alter table public.gmax_events enable row level security;
